# Generated by Django 2.1.15 on 2022-07-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Name')),
                ('type', models.TextField(max_length=20, verbose_name='Type')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('telephone', models.TextField(max_length=15, verbose_name='Telephone')),
            ],
        ),
    ]
